title: Harmonia in China
author: Zehao Wang
email: water45wzh@pku.edu.cn
description: >-
  Harmonia demo page for Chinese users.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://harmonia.illiacsoftware.cn" # your site's origin, e.g. https://forestry.io

# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html

plugins:
  - jekyll-feed
  - jekyll-menus

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
